### ISSUE TITLE
esbuild version mismatch

### ISSUE THREAD

**Issue by orekav** [sudokar/cdk-appsync-typescript-resolver#24]
When there is a mismatch between the esbuild versions in the project and this package an error is thrown during package installation.

```sh
[-/11] ⠐ waiting...
[7/11] ⠐ nx
[10/11] ⠐ esbuild
error /Users/___/Workspace/___/___/node_modules/cdk-appsync-typescript-resolver/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/___/Workspace/___/___/node_modules/cdk-appsync-typescript-resolver/node_modules/esbuild
Output:
/Users/___/Workspace/___/___/node_modules/cdk-appsync-typescript-resolver/node_modules/esbuild/install.js:132
    throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
          ^

Error: Expected "0.19.2" but got "0.19.12"
    at validateBinaryVersion (/Users/___/Workspace/___/___/node_modules/cdk-appsync-typescript-resolver/node_modules/esbuild/install.js:132:11)
```

In order to reproduce it
1 - create a package.json with esbuild@0.20.0
2 - install dependencies
3 - add cdk-appsync-typescript-resolver@0.0.22

Wouldn't this issue fixed if esbuild were a `peerDependency` instead of a `dependency` ?

**Comment by sudokar** [comment]
Hey @orekav , Thanks for reporting this :)

I kept it as dependency thinking that, this construct can be extended to be usable in other languages supported by CDK. It is also part of `bundledDependencies`. It is a good point that we can keep it as peerDep to avoid this issue. I will make a new release for this.

**Comment by richard-jfc** [comment]
Just had this issue today, @sudokar looks like you never merged that PR. Any plans to fix this?
