### ISSUE TITLE
Feat: Add utility for creating resolvers from an array of object

### ISSUE THREAD

**Issue by ShivamJoker** [sudokar/cdk-appsync-typescript-resolver#5]
Right now we have to do this to create one resolver:

```ts
    const appsyncFunction = new AppsyncTypescriptFunction(
      this,
      "getVideoUploadUrl",
      {
        api: gqlApi,
        dataSource: cloudflareHttpDataSrc,
        name: "getVideoUploadUrl",
        path: joinPath(__dirname, "../resolvers/getVideoUploadUrl.ts"),
        replaceStrings: {
          CF_STREAMS_TOKEN,
          CF_ACCOUNT_ID,
        },
        sourceMap: true,
      },
    );

    const resolver = new TSExpressPipelineResolver(this, "DemoResolver", {
      api: gqlApi,
      typeName: "Query",
      fieldName: "getVideoUploadUrl",
      tsFunction: appsyncFunction,
    });
```

If we can have some utility function which will just take the file name and path for the resolvers it'll make building multiple resolvers really easy.

Thanks for your work.

**Comment by sudokar** [comment]
You're welcome!

Do you mean an utility for resolver to accept multiple functions/paths with respective properties like typeName, fieldName, dataSource, etc?

**Comment by ShivamJoker** [comment]
Yes. I had created similar util but it would be helpful to get it from this library only.

**Comment by sudokar** [comment]
IMHO, it is better to leave it with the developers, who uses it, to create appropriate utils suited for their needs. For example, we have NodejsFunction construct from CDK and we either extend or build an utility with the default properties we need set. Hope this helps 😄
